// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComparable(arg1, arg2) {
  return window['go']['main']['App']['AddComparable'](arg1, arg2);
}

export function AddToWatchlist(arg1) {
  return window['go']['main']['App']['AddToWatchlist'](arg1);
}

export function AnalyzeStock(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeStock'](arg1, arg2);
}

export function AnalyzeStockWithRIM(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeStockWithRIM'](arg1, arg2, arg3);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CheckAnalysisCache(arg1) {
  return window['go']['main']['App']['CheckAnalysisCache'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckPythonDependencies() {
  return window['go']['main']['App']['CheckPythonDependencies']();
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function DeleteReport(arg1, arg2) {
  return window['go']['main']['App']['DeleteReport'](arg1, arg2);
}

export function DownloadComparableReports(arg1) {
  return window['go']['main']['App']['DownloadComparableReports'](arg1);
}

export function DownloadReport(arg1, arg2) {
  return window['go']['main']['App']['DownloadReport'](arg1, arg2);
}

export function DownloadReports(arg1, arg2) {
  return window['go']['main']['App']['DownloadReports'](arg1, arg2);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function ExportCurrentFinancialData(arg1) {
  return window['go']['main']['App']['ExportCurrentFinancialData'](arg1);
}

export function ExportFinancialDataToExcel(arg1) {
  return window['go']['main']['App']['ExportFinancialDataToExcel'](arg1);
}

export function ExportHistoricalFinancialData(arg1, arg2) {
  return window['go']['main']['App']['ExportHistoricalFinancialData'](arg1, arg2);
}

export function ExportReportImage(arg1, arg2) {
  return window['go']['main']['App']['ExportReportImage'](arg1, arg2);
}

export function ExportReportPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportReportPDF'](arg1, arg2);
}

export function FetchHotConceptConstituents(arg1) {
  return window['go']['main']['App']['FetchHotConceptConstituents'](arg1);
}

export function FetchHotConceptHistory(arg1) {
  return window['go']['main']['App']['FetchHotConceptHistory'](arg1);
}

export function FetchHotConcepts(arg1) {
  return window['go']['main']['App']['FetchHotConcepts'](arg1);
}

export function FetchMissingActivity(arg1) {
  return window['go']['main']['App']['FetchMissingActivity'](arg1);
}

export function GetAutoCheckUpdate() {
  return window['go']['main']['App']['GetAutoCheckUpdate']();
}

export function GetComparables(arg1) {
  return window['go']['main']['App']['GetComparables'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetFinancialTrends(arg1) {
  return window['go']['main']['App']['GetFinancialTrends'](arg1);
}

export function GetIndustryDBMeta() {
  return window['go']['main']['App']['GetIndustryDBMeta']();
}

export function GetIndustryMetrics(arg1) {
  return window['go']['main']['App']['GetIndustryMetrics'](arg1);
}

export function GetIndustryTaskStatus() {
  return window['go']['main']['App']['GetIndustryTaskStatus']();
}

export function GetIntradayMinutes(arg1) {
  return window['go']['main']['App']['GetIntradayMinutes'](arg1);
}

export function GetMarketCacheStatus() {
  return window['go']['main']['App']['GetMarketCacheStatus']();
}

export function GetModule4Status(arg1) {
  return window['go']['main']['App']['GetModule4Status'](arg1);
}

export function GetPolicyLibraryMeta() {
  return window['go']['main']['App']['GetPolicyLibraryMeta']();
}

export function GetReport(arg1, arg2) {
  return window['go']['main']['App']['GetReport'](arg1, arg2);
}

export function GetReportHistory(arg1) {
  return window['go']['main']['App']['GetReportHistory'](arg1);
}

export function GetRiskRadar(arg1, arg2) {
  return window['go']['main']['App']['GetRiskRadar'](arg1, arg2);
}

export function GetRiskSensitivity() {
  return window['go']['main']['App']['GetRiskSensitivity']();
}

export function GetSFLConfig() {
  return window['go']['main']['App']['GetSFLConfig']();
}

export function GetSnapshotHistory(arg1) {
  return window['go']['main']['App']['GetSnapshotHistory'](arg1);
}

export function GetStockConcepts(arg1) {
  return window['go']['main']['App']['GetStockConcepts'](arg1);
}

export function GetStockDataHistory(arg1) {
  return window['go']['main']['App']['GetStockDataHistory'](arg1);
}

export function GetStockKlines(arg1, arg2) {
  return window['go']['main']['App']['GetStockKlines'](arg1, arg2);
}

export function GetStockMoneyflow(arg1, arg2) {
  return window['go']['main']['App']['GetStockMoneyflow'](arg1, arg2);
}

export function GetStockProfile(arg1) {
  return window['go']['main']['App']['GetStockProfile'](arg1);
}

export function GetStockQuote(arg1) {
  return window['go']['main']['App']['GetStockQuote'](arg1);
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function GetWatchlistActivity() {
  return window['go']['main']['App']['GetWatchlistActivity']();
}

export function GetWatchlistFilterData() {
  return window['go']['main']['App']['GetWatchlistFilterData']();
}

export function HasPythonDepsChecked() {
  return window['go']['main']['App']['HasPythonDepsChecked']();
}

export function ImportFinancialReports(arg1) {
  return window['go']['main']['App']['ImportFinancialReports'](arg1);
}

export function InitIndustryDatabase() {
  return window['go']['main']['App']['InitIndustryDatabase']();
}

export function InstallPythonDependencies(arg1) {
  return window['go']['main']['App']['InstallPythonDependencies'](arg1);
}

export function LoadAnalysisSnapshot(arg1) {
  return window['go']['main']['App']['LoadAnalysisSnapshot'](arg1);
}

export function LoadSnapshotByTime(arg1, arg2) {
  return window['go']['main']['App']['LoadSnapshotByTime'](arg1, arg2);
}

export function MarkPythonDepsChecked() {
  return window['go']['main']['App']['MarkPythonDepsChecked']();
}

export function QuickAnalyzeStock(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QuickAnalyzeStock'](arg1, arg2, arg3, arg4);
}

export function RecommendComparables(arg1) {
  return window['go']['main']['App']['RecommendComparables'](arg1);
}

export function RefreshIndustryBaselines() {
  return window['go']['main']['App']['RefreshIndustryBaselines']();
}

export function RefreshMarketCache() {
  return window['go']['main']['App']['RefreshMarketCache']();
}

export function RefreshStockKlines(arg1, arg2) {
  return window['go']['main']['App']['RefreshStockKlines'](arg1, arg2);
}

export function RefreshStockProfile(arg1) {
  return window['go']['main']['App']['RefreshStockProfile'](arg1);
}

export function ReloadIndustryDatabase() {
  return window['go']['main']['App']['ReloadIndustryDatabase']();
}

export function ReloadPolicyLibrary() {
  return window['go']['main']['App']['ReloadPolicyLibrary']();
}

export function RemoveComparable(arg1, arg2) {
  return window['go']['main']['App']['RemoveComparable'](arg1, arg2);
}

export function RemoveFromWatchlist(arg1) {
  return window['go']['main']['App']['RemoveFromWatchlist'](arg1);
}

export function ReorderWatchlist(arg1) {
  return window['go']['main']['App']['ReorderWatchlist'](arg1);
}

export function SaveDefaultPolicyLibrary() {
  return window['go']['main']['App']['SaveDefaultPolicyLibrary']();
}

export function SaveSFLConfig(arg1) {
  return window['go']['main']['App']['SaveSFLConfig'](arg1);
}

export function SearchStocks(arg1) {
  return window['go']['main']['App']['SearchStocks'](arg1);
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SetAutoCheckUpdate(arg1) {
  return window['go']['main']['App']['SetAutoCheckUpdate'](arg1);
}

export function SetRiskSensitivity(arg1) {
  return window['go']['main']['App']['SetRiskSensitivity'](arg1);
}

export function SkipVersion(arg1) {
  return window['go']['main']['App']['SkipVersion'](arg1);
}

export function UpdateIndustryDatabase() {
  return window['go']['main']['App']['UpdateIndustryDatabase']();
}

export function UpdateModule4Only(arg1) {
  return window['go']['main']['App']['UpdateModule4Only'](arg1);
}

export function UpdatePolicyLibrary() {
  return window['go']['main']['App']['UpdatePolicyLibrary']();
}

export function VerifySFLToken(arg1) {
  return window['go']['main']['App']['VerifySFLToken'](arg1);
}
