// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analyzer} from '../models';
import {ai_researcher} from '../models';
import {main} from '../models';
import {updater} from '../models';
import {downloader} from '../models';

export function AddComparable(arg1:string,arg2:string):Promise<void>;

export function AddToWatchlist(arg1:string):Promise<void>;

export function AnalyzeStock(arg1:string,arg2:boolean):Promise<analyzer.AnalysisReport>;

export function AnalyzeStockWithAI(arg1:string,arg2:string,arg3:boolean):Promise<ai_researcher.AIResearchReport>;

export function AnalyzeStockWithRIM(arg1:string,arg2:boolean,arg3:string):Promise<analyzer.AnalysisReport>;

export function ApplyUpdate(arg1:string):Promise<void>;

export function CancelAIResearch(arg1:string):Promise<void>;

export function CheckAnalysisCache(arg1:string):Promise<main.CacheStatus>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function CheckPythonDependencies():Promise<main.PythonEnvResult>;

export function ClipboardGetText():Promise<string>;

export function ClipboardSetText(arg1:string):Promise<void>;

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function DeleteReport(arg1:string,arg2:string):Promise<void>;

export function DownloadComparableReports(arg1:string):Promise<main.DownloadResult>;

export function DownloadReport(arg1:string,arg2:string):Promise<void>;

export function DownloadReports(arg1:string,arg2:number):Promise<main.DownloadResult>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<string>;

export function ExportAIResearchMd(arg1:string,arg2:string):Promise<void>;

export function ExportAIResearchPdf(arg1:string,arg2:string):Promise<void>;

export function ExportAIResearchTxt(arg1:string,arg2:string):Promise<void>;

export function ExportCurrentFinancialData(arg1:string):Promise<void>;

export function ExportFinancialDataToExcel(arg1:string):Promise<void>;

export function ExportHistoricalFinancialData(arg1:string,arg2:string):Promise<void>;

export function ExportReportImage(arg1:string,arg2:string):Promise<void>;

export function ExportReportPDF(arg1:string,arg2:string):Promise<void>;

export function FetchHotConceptConstituents(arg1:string,arg2:string):Promise<Array<downloader.ConceptConstituent>>;

export function FetchHotConceptHistory(arg1:number):Promise<Array<downloader.HotConceptHistoryItem>>;

export function FetchHotConcepts(arg1:number):Promise<downloader.HotConceptBoard>;

export function FetchMissingActivity(arg1:Array<string>):Promise<main.FetchMissingActivityResult>;

export function GetAIConfig():Promise<ai_researcher.AIConfig>;

export function GetAutoCheckUpdate():Promise<boolean>;

export function GetComparables(arg1:string):Promise<Array<string>>;

export function GetCurrentVersion():Promise<string>;

export function GetFinancialTrends(arg1:string):Promise<main.FinancialTrendsData>;

export function GetIndustryDBMeta():Promise<Record<string, any>>;

export function GetIndustryMetrics(arg1:string):Promise<analyzer.IndustryMetrics|boolean>;

export function GetIndustryTaskStatus():Promise<Record<string, any>>;

export function GetIntradayMinutes(arg1:string):Promise<downloader.IntradayData>;

export function GetLatestMargin(arg1:string):Promise<downloader.MarginData>;

export function GetMarginHistory(arg1:string,arg2:boolean):Promise<Array<downloader.MarginData>>;

export function GetMarketCacheStatus():Promise<Record<string, any>>;

export function GetModule4Status(arg1:string):Promise<boolean>;

export function GetPolicyLibraryMeta():Promise<Record<string, string>>;

export function GetReport(arg1:string,arg2:string):Promise<string>;

export function GetReportHistory(arg1:string):Promise<Array<string>>;

export function GetRiskRadar(arg1:string,arg2:string):Promise<Array<analyzer.RiskRadarItem>>;

export function GetRiskSensitivity():Promise<string>;

export function GetSFLConfig():Promise<main.SFLConfig>;

export function GetSnapshotHistory(arg1:string):Promise<Array<main.SnapshotInfo>>;

export function GetStockConcepts(arg1:string):Promise<downloader.StockConcepts>;

export function GetStockDataHistory(arg1:string):Promise<Array<main.HistoryMeta>>;

export function GetStockKlines(arg1:string,arg2:string):Promise<Array<downloader.KlineData>>;

export function GetStockMoneyflow(arg1:string,arg2:number):Promise<main.StockMoneyflowResult>;

export function GetStockProfile(arg1:string):Promise<main.StockProfile>;

export function GetStockQuote(arg1:string):Promise<downloader.StockQuote>;

export function GetWatchlist():Promise<Array<main.WatchlistItem>>;

export function GetWatchlistActivity():Promise<Array<main.WatchlistActivitySummary>>;

export function GetWatchlistFilterData():Promise<Array<main.WatchlistFilterItem>>;

export function HasPythonDepsChecked():Promise<boolean>;

export function ImportFinancialReports(arg1:string):Promise<main.ImportResult>;

export function InitIndustryDatabase():Promise<void>;

export function InstallPythonDependencies(arg1:Array<string>):Promise<void>;

export function LoadAIResearchReport(arg1:string):Promise<ai_researcher.AIResearchReport>;

export function LoadAnalysisSnapshot(arg1:string):Promise<analyzer.AnalysisReport>;

export function LoadSnapshotByTime(arg1:string,arg2:string):Promise<analyzer.AnalysisReport>;

export function MarkPythonDepsChecked():Promise<void>;

export function QuickAnalyzeStock(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.QuickAnalysis>;

export function RecommendComparables(arg1:string):Promise<Array<analyzer.ComparableRecommendation>>;

export function RefreshIndustryBaselines():Promise<Record<string, analyzer.IndustryBaseline>>;

export function RefreshInteractQA(arg1:string):Promise<Array<analyzer.InteractQA>>;

export function RefreshMarketCache():Promise<string>;

export function RefreshStockKlines(arg1:string,arg2:string):Promise<Array<downloader.KlineData>>;

export function RefreshStockProfile(arg1:string):Promise<main.StockProfile>;

export function ReloadIndustryDatabase():Promise<void>;

export function ReloadPolicyLibrary():Promise<void>;

export function RemoveComparable(arg1:string,arg2:string):Promise<void>;

export function RemoveFromWatchlist(arg1:string):Promise<void>;

export function ReorderWatchlist(arg1:Array<string>):Promise<void>;

export function SaveAIConfig(arg1:ai_researcher.AIConfig):Promise<void>;

export function SaveDefaultPolicyLibrary():Promise<void>;

export function SaveSFLConfig(arg1:main.SFLConfig):Promise<void>;

export function SearchStocks(arg1:string):Promise<Array<main.StockInfo>>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SetAutoCheckUpdate(arg1:boolean):Promise<void>;

export function SetRiskSensitivity(arg1:string):Promise<void>;

export function SkipVersion(arg1:string):Promise<void>;

export function TestAIConnection(arg1:ai_researcher.AIConfig):Promise<ai_researcher.TestConnectionResult>;

export function UpdateIndustryDatabase():Promise<downloader.IndustryUpdateResult>;

export function UpdateModule4Only(arg1:string):Promise<analyzer.AnalysisReport>;

export function UpdatePolicyLibrary():Promise<downloader.PolicyUpdateResult>;

export function VerifySFLToken(arg1:string):Promise<main.SFLVerifyResult>;
